Reviewed and improved the Shapes API server code, docs and stack script.
Signed-off-by: Exadra37 <exadra37@gmail.com>

diff --git a/servers/shapes-api/stack b/servers/shapes-api/stack
--- a/servers/shapes-api/stack
+++ b/servers/shapes-api/stack
@@ -24,6 +24,11 @@ function Create_Docker_Container
     local _server_name="${4? Missing server name for the container we want to stop!!!}"
     local _container_name="python-flask-${_server_name}"
 
+    if [ ! -f "./.env" ]; then
+        printf "\n ---> ERROR: Missing .env file. Copy .env.example to .env and customize it.\n\n"
+        exit 1
+    fi
+
     sudo docker run \
         -it \
         --rm \
